### ISSUE TITLE
Odd behavior on MS Edge browser

### ISSUE THREAD

**Issue by joaodiaslobo** [joinum/parzival#328]
Add the following CSS code to app.css to disable the toggle Microsoft Edge adds to show the password

```css
/* Hide password reveal button in MS Edge */
::-ms-reveal {
  display: none;
}
```
